### PR TITLE
Tests packaging and oh my, it workz

### PR DESCRIPTION
**Pull request by erikzaadi**
- [x] Initials tests
- [x] Travis to push package on tags
- [x] Fix shahar's bugs
- [x] Set version dynamically by tag
- [x] Refactor configure and alert to be more testable

@hkariti, @shaharke view bematuta

### CODE REVIEW

**Comment by hkariti** [comment]
15 files!?

**Comment by erikzaadi** [comment]
@hkariti you have 17 minutes, GO GO GO

**Comment by hkariti** [comment]
build related things look ok

**Comment by shaharke** [comment]
+1

—

**Pull request merged**
